version: '3'

services:
  maildev:
    image: 'maildev/maildev'
    ports:
      - '1080:1080'
      - '1025:1025'

  redis:
    image: 'redis/redis-stack'
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis-state:/data

  synapse_database:
    image: 'postgres:16'
    ports:
      - '5432:5432'
    volumes:
      - synapse_database:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  synapse:
    image: 'ghcr.io/element-hq/synapse:v1.100.0'
    ports:
      - '8008:8008'
      - '8448:8448'
    volumes:
      - ./docker/synapse:/data
    env_file:
      - .env
    restart: always
    network_mode: 'host'
    depends_on:
      - synapse_database

volumes:
  redis-state:
  synapse_database:
