[package]
name = "matrix"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.74"
hex = "0.4.3"
hmac = "0.12.1"
serde_path_to_error = "0.1.14"
serde_qs = "0.12.0"
sha1 = "0.10.6"
ruma = { version = "0.9.4", features = ["events", "rand"] }
ruma-macros = "0.12.0"

# Workspace Dependencies
anyhow = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }
