[package]
name = "matrix"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ruma-events = { version = "0.27.11", features = ["html", "markdown"] }
ruma-common = { version = "0.12.0", features = ["api", "rand"], default_features = false }
ruma-macros = "0.12.0"

# Workspace Dependencies
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
mime = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }
