name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    paths:
      - "**"
      - "!/*.md"
      - "!/**.md"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Check clippy
        run: cargo clippy --workspace -- -D warnings

      - name: Unit Tests
        run: cargo test -p matrix

      - name: Install Just
        uses: extractions/setup-just@v1
        with:
          just-version: '1.13.0'

      - name: Create a copy of `.env.example`
        run: just dotenv

      - name: Generate Synapse Configuration
        run: |
          just gen_synapse_conf

      - name: Use Test Homeserver
        run: |
          sudo cp -f ./crates/test/fixtures/synapse/homeserver.yaml ./docker/synapse/homeserver.yaml

      - name: Run Docker Containers
        run: |
          docker compose up -d
          sleep 10

      - name: Create Admin User
        run: just gen_synapse_admin

      - name: Retrieve Admin Access Token
        run: |
          just get_access_token
          export COMMUNE_SYNAPSE_ADMIN_TOKEN=$(cat ./access_token.txt)
          echo "COMMUNE_SYNAPSE_ADMIN_TOKEN=${COMMUNE_SYNAPSE_ADMIN_TOKEN}" >> $GITHUB_ENV

      - name: E2E Tests
        env:
          COMMUNE_SYNAPSE_ADMIN_TOKEN: ${{ env.COMMUNE_SYNAPSE_ADMIN_TOKEN }}
        run: |
          cargo test -p test -- --test-threads=1

      - name: Print Logs
        if: always()
        run: |
          docker-compose logs --no-color --tail=1000 synapse > synapse.log
          cat ./synapse.log
          docker compose down
          docker ps
